<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="4.152.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RealmStudioShapeRenderingLib\RealmStudioShapeRenderingLib.csproj" />
    <ProjectReference Include="..\RealmStudioX.Core\RealmStudioX.Core.csproj" />
  </ItemGroup>

</Project>
